/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	__asm ("SVC #24");
	uint8_t ret_svc;
	__asm volatile("MOV %0, R0":"=r"(ret_svc)::);
	printf("ret_svc -> %d\n",ret_svc);
	for(;;);
}

__attribute((naked)) void SVC_Handler(void)
{
	__asm ("MRS R0, MSP");
	__asm("b SVC_Handler_C");
}
void SVC_Handler_C(uint32_t *pBaseOfStackFrame)
{
	printf("In SVC Handler\n");
	printf("pBaseOfStackFrame -> %p\n",pBaseOfStackFrame);
	uint8_t *pPC =  (uint8_t *)pBaseOfStackFrame[6];
	printf("PC -> %p\n",pPC);
	pPC -=2;
	uint8_t svc_no = *pPC;
	printf("SVC Number -> %d\n",svc_no);
	svc_no += 4;
	pBaseOfStackFrame[0] = svc_no;
}
