/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define NVIC_ISER_BASE 0xE000E100
#define NVIC_ISPR_BASE 0XE000E200
#define NVIC_IPR_BASE 0xE000E400

#define TIM2_IRQ 28
#define I2C1_EV_IRQ 31

void configure_priority(uint32_t int_no, uint8_t priority_value)
{
	//find out IPRx
	uint8_t IPRx = int_no / 4;
	uint32_t *pIPR = (uint32_t *) (NVIC_IPR_BASE + (4 *IPRx));

	// find position in IPRx
	uint32_t pos = (int_no % 4) * 8;

	//configure the priority
	*pIPR &= ~(0xFF << pos); // clear bits
	*pIPR |= (priority_value << pos);
}

void pend_interrupt(uint32_t IRQ_NO)
{
	//find Int set pending reg no
	uint8_t ISPRx = IRQ_NO / 32;

	// int set pend reg addr
	uint32_t *pISPR = (uint32_t *) (NVIC_ISPR_BASE + (ISPRx * 4));

	//pend interrupt
	*pISPR |= (1 << (IRQ_NO % 32));
}

void enable_IRQ(uint32_t IRQ_NO)
{
	//find ISERx number
	uint8_t ISPRx = IRQ_NO / 32;

	//find ISPR reg addr
	uint32_t *pISPR = (uint32_t *) (NVIC_ISER_BASE + (ISPRx * 4));

	//enable IRQ
	*pISPR |= (1 << (IRQ_NO % 32));
}

int main(void)
{

	//Configure the priority for the peripherals
	configure_priority(TIM2_IRQ, 0x80);
	configure_priority(I2C1_EV_IRQ, 0x70); // try with 0x80 as well

	// set the interrupt bit in NVIC PR
	pend_interrupt(TIM2_IRQ);


	// enable the IRQs in NVIC ISER

	enable_IRQ(I2C1_EV_IRQ);
	enable_IRQ(TIM2_IRQ);

    /* Loop forever */
	for(;;);
}

void TIM2_IRQHandler(void)
{
	printf("In TIM2_IRQHandler \n");
	pend_interrupt(I2C1_EV_IRQ);
	printf("after pending i2c");
	while(1);
}
void I2C1_EV_IRQHandler(void)
{
	printf("In I2C1_EV_IRQHandler \n");
}
